modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="adventurepls"
version="1.0.0"
displayName="AdventurePls"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Ofir, MCreator"

[[dependencies.adventurepls]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




